workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 120
        instance_type: mac_pro
        environment:
            groups:
                - g
            android_signing:
                - key1
            vars:
                PACKAGE_NAME: "com.myreactnative"
            # node: v16.11.1
        triggering:
            events:
                - tag
            tag_patterns:
                - pattern: '*'
                  include: true
        scripts:
            - name: Install npm dependencies
              script: |
                npm install
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"          
            - name: Build Android release
              script: |
                #export BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
                cd android && chmod +x gradlew
                ./gradlew assembleRelease
            - name: Build finished successfully
              script: touch ~/SUCCESS
        artifacts:
            - android/app/build/outputs/**/**/*.apk
        publishing:
          email:
            recipients:
              - kalgi@nevercode.io
          scripts:
            - name: Report Build status
              script: |   
                if [ -f ~/SUCCESS ] ; then
                echo "build successful"
                else
                echo "build failed"
                fi
